### ISSUE TITLE
Static built library not including ZLib symbols

### ISSUE THREAD

**Issue by antoine-morvan** [HDFGroup/hdf5#2498] opened 2023-02-24 16:04 UTC
Hello,

**Describe the bug**
When building a static version of HDF5, with ZLib support linked statically, the built `libhdf5.a` does not reference ZLib symbols. 
This is not consistent with the dybamic version of HDF5, with ZLib support linked statically, which does include ZLib symbols:

```
$ nm hdf5/prefix/lib/libhdf5.so | grep inflate
00000000002f1020 T inflate
00000000002f3b80 T inflateCodesUsed
00000000002f3790 T inflateCopy
00000000002f31d0 T inflateEnd
[...]

$ nm hdf5/prefix/lib/libhdf5.a | grep inflate
                 U inflate
                 U inflateEnd
                 U inflateInit_
```

Consequently, when building binaries against the static version of HDF5 with ZLib support, the build system fails at referencing these ZLib symbols:
```
ld: FULLPATHHIDDEN/hdf5/prefix/lib/libhdf5.a(H5Zdeflate.c.o): in function `H5Z__filter_deflate':
FULLPATHHIDDEN/hdf5/hdf5-1.13.2/src/H5Zdeflate.c:103: undefined reference to `inflateInit_'
ld: FULLPATHHIDDEN/hdf5/hdf5-1.13.2/src/H5Zdeflate.c:109: undefined reference to `inflate'
ld: FULLPATHHIDDEN/hdf5/hdf5-1.13.2/src/H5Zdeflate.c:174: undefined reference to `compress2'
ld: FULLPATHHIDDEN/hdf5/hdf5-1.13.2/src/H5Zdeflate.c:128: undefined reference to `inflateEnd'
ld: FULLPATHHIDDEN/hdf5/hdf5-1.13.2/src/H5Zdeflate.c:117: undefined reference to `inflateEnd'
ld: FULLPATHHIDDEN/hdf5/hdf5-1.13.2/src/H5Zdeflate.c:151: undefined reference to `inflateEnd'
make[2]: *** [test/solver/CMakeFiles/test_solver.dir/build.make:191: test/solver/test_solver] Error 1
```

**Expected behavior**
The behavior should be the same when building either the dynamic or static HDF5 library with ZLib support, ZLib linked statically: `libhdf5.a` should not have undefined ZLib symbols, as these are not system symbols.

**Platform (please complete the following information)**
 - HDF5 version : 1.13.2
 - OS and version: Linux, tried on RHEL 8; rocky 9; ubuntu 20.04
 - Compiler and version: Tried on OneAPI classic (icc) 2023.0.0; OneAPI clasisc (icc) 2022.3.0; GCC 8.5
 - Build system (e.g. CMake, Autotools) and version: tried CMake 3.25.2; CMake 3.20.1; CMake 3.16.1
 - Any configure options you specified: `-DBUILD_SHARED_LIBS=ON  -DBUILD_STATIC_LIBS=ON -DHDF5_ENABLE_Z_LIB_SUPPORT=ON -DZLIB_USE_STATIC_LIBS=ON`
 - MPI library and version (parallel HDF5): Tried with and without parallel flags; Intel MPI & OpenMPI 4.1.4 (but not relevant here I guess).

**Additional context**
I identified the `ar` command used to build the static library to only include built `.o`, and not `libz.a`, whereas the `cc` command building the shared library does reference `libz.a`:
```bash
## shared build
/usr/bin/cc -fPIC -std=c99  -fstdarg-opt -fmessage-length=0 -O2 -g -DNDEBUG -shared -Wl,-soname,libhdf5.so.302 
	-o ../bin/libhdf5.so.302.0.0  	[FULL_LIST_OF_HDF5_OBJECT_FILES]  	-Wl,-rpath,"\$ORIGIN/../lib:\$ORIGIN/"
	-lm -ldl FULLPATHHIDDEN/zlib/prefix/lib/libz.a -ldl FULLPATHHIDDEN/zlib/prefix/lib/libz.a 

## static build
/usr/bin/ar qc ../bin/libhdf5.a [FULL_LIST_OF_HDF5_OBJECT_FILES]
```
This is visible in `05_hdf5_make.log` produced by the script below.

Here is a script to reproduce (assuming cmake & $CC available):
https://github.com/antoine-morvan/hdf5-reproducer-08e548e9/blob/main/reproduce.sh

:warning: Also, please note that having a LDCache populated with ZLib will most likely hide this issue. 

Cheers.

**Comment by byrnHDF** [comment] 2023-02-24 16:55
I'm thinking that this is how static libs are by design and why you have to include the dependent static libs on the link line.

**Comment by byrnHDF** [comment] 2023-02-24 20:08
Searching provides this comment:   A static library is not linked, think of it as a zip of object files. Linking only occurs on executables and shared libraries.

**Comment by byrnHDF** [comment] 2023-03-09 14:15
> Searching provides this comment: A static library is not linked, think of it as a zip of object files. Linking only occurs on executables and shared libraries.

Removing bug type label due this comment.

**Comment by byrnHDF** [comment] 2023-05-04 15:48
Closing this as any further discussion should happen on this issue should happen on the Forum or the Discussion page.

**Closed as completed by byrnHDF** 2023-05-04 15:48 UTC
Labels: Component - Build
