### ISSUE TITLE
Access violation at H5MM_memcpy

### ISSUE THREAD

**Issue by ihna-ceres** [HDFGroup/hdf5#2088] opened 2022-09-07 06:52 UTC
**Describe the bug**
My program frequently writes data to h5 file.

It usually works well, but sometimes Access violation error occurs at write function.
By using debugger, I could find that it occurs at H5MM_memcpy function at H5MM.c:617:
`ret = HDmemcpy(dest, src, n);`
I also could find that this occurs because src has value of 0x00000001.
I want to know why this error is occured and how to prevent this.
I attach erorr messages,  call stack, and my code below. 

I use highfive library (c++ wrapper for hdf5), but I don't think that's the reason.

**Platform (please complete the following information)**
- Windows Server 2019
- Visual Studio 2022 (c++, x86)
- I use vcpkg to install libraries
- hdf5 version: 1.12.2#1 (x86 windows)

**Additional context**
## Error message
H5MM.c:617 (debugger says that src has the value of 0x00000001)
![image](https://user-images.githubusercontent.com/106783889/188807520-89ef125f-7985-411a-b4fd-4fa682bd639d.png)

## Variables
![image](https://user-images.githubusercontent.com/106783889/188809270-7a4763f5-48ae-4afb-9a48-42a96065456e.png)

## Call stack
![image](https://user-images.githubusercontent.com/106783889/188808089-e8f0732c-bc41-46c6-a053-a1c7ef76a138.png)

## My code
![image](https://user-images.githubusercontent.com/106783889/188808252-7ca22ae8-d043-40ce-b574-8a9710c8222c.png)

## Variables in my code
![image](https://user-images.githubusercontent.com/106783889/188809427-7c5a0616-340d-4f0b-a3d3-9f48069eb13d.png)
(All variables are set as intended)

**Comment by derobins** [comment] 2023-06-13 17:06
Can you provide a C reproducer? This looks like a problem with either your code or the wrapper, not the library.

**Comment by derobins** [comment] 2024-03-25 01:33
Without a reproducer, we can't address this. Closing, but feel free to reopen if you can get us something we can use to investigate.

**Closed as completed by derobins** 2024-03-25 01:33 UTC
Labels: Component - C Library
