### ISSUE TITLE
Conditional statements in hdf5-targets.cmake break link.txt

### ISSUE THREAD

**Issue by robin-deltares** [HDFGroup/hdf5#2935] opened 2023-05-10 09:54 UTC
**Describe the bug**
Error when building, for people who google this:
```
gmake[2]: *** No rule to make target '/opt/apps/openmpi/4.1.5_gcc12.2.0/lib/libmpi.so>', needed by 'bin/libhdf5
gmake[1]: *** [CMakeFiles/Makefile2:1906: fortran/src/CMakeFiles/hdf5_fortran-shared.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

hdf5-targets.cmake example:
`INTERFACE_LINK_LIBRARIES "hdf5-static;\$<LINK_ONLY:\$<\$<BOOL:ON>:MPI::MPI_C>>"`

hdf5_fortran-shared.dir/build.make example:
`bin/libhdf5_fortran.so.310.0.0: /opt/apps/openmpi/4.1.5_gcc12.2.0/lib/libmpi.so>`

link.txt example:
` -ldl $<1:/opt/apps/openmpi/4.1.5_gcc12.2.0/lib/libmpi_usempif08.so /opt/apps/openmpi/4.1.5_gcc12.2.0/lib/libmpi.so "/opt/apps/openmpi/4.1.5_gcc12.2.0/lib/libmpi.so>`

**Expected behavior**
When I remove the occurrences of `$<1` and `>` the linking/build succeeds, so the expected behavior is that these will not appear in build.make and link.txt.

**Platform (please complete the following information)**
 - HDF5 version: 1.14.0
 - OS and version: AlmaLinux 8
 - Compiler and version: GCC 12.2.0
 - Build system (e.g. CMake, Autotools) and version: CMake 3.26.1
 - Any configure options you specified:
```
 cmake .. \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DHDF5_BUILD_FORTRAN=ON \
    -DBUILD_TESTING=OFF \
    -DHDF5_ENABLE_Z_LIB_SUPPORT=ON \
    -DHDF5_ENABLE_PARALLEL=ON \
    -DHDF5_ENABLE_TRACE=ON \
    -DHDF5_ENABLE_DEPRECATED_SYMBOLS=OFF \
    -DHDF5_BUILD_EXAMPLES=OFF \
    -DHDF5_BUILD_HL_LIB=OFF
```
 - MPI library and version (parallel HDF5): OpenMPI 4.1.5

**Additional context**
I do not know if this is a problem with CMake or the scripts from this repo.

**Comment by byrnHDF** [comment] 2023-05-10 13:23
We believe this is the same issue as #2906.  The problem is that generator expressions were not being parsed correctly resulting in issues like this. This has been fixed in the development branches and for the 1.14.1 release this week.

**Comment by byrnHDF** [comment] 2023-05-16 13:52
Please let us know if this is still a problem with the 1.14.1 release.

**Comment by robin-deltares** [comment] 2023-05-17 13:45
Flawless, thank you! 🤗

**Closed as completed** 2023-05-17 13:49 UTC
Labels: Component - Build
