### ISSUE TITLE
CMake build is missing H5FDsubfiling.h

### ISSUE THREAD

**Issue by diiigle** [HDFGroup/hdf5#3037] opened 2023-06-02 18:26 UTC
Abstract: When building with CMake from git source, an include directory is missing in the target `INTERFACE` of `hdf5-static`.

`hdf5\src\hdf5.h(74): fatal error C1083: Cannot open include file: 'H5FDsubfiling.h': No such file or directory`

**Describe the bug**
I am building the library as a submodule from the git source tree (not a released zip). 
When I `#include <hdf5.h>` in my code, the pre-processor can't find `H5FDsubfiling.h`.

I was digging into the build system and [it seems like](https://github.com/HDFGroup/hdf5/blob/81bc34ac4c3f42532edee32095651f6bcd5e55a2/CMakeLists.txt#L721) the necessary directories get added to `${HDF5_SRC_INCLUDE_DIRS}`. Then when the library target is created this variable is not used for the `INTERFACE` of the library, meaning its include directories propagate to dependent targets in CMake. This is both true for the [static](https://github.com/HDFGroup/hdf5/blob/81bc34ac4c3f42532edee32095651f6bcd5e55a2/src/CMakeLists.txt#L1235) and [shared](https://github.com/HDFGroup/hdf5/blob/81bc34ac4c3f42532edee32095651f6bcd5e55a2/src/CMakeLists.txt#L1276) version.

When I modify these lines to `$<BUILD_INTERFACE:${HDF5_SRC_BINARY_DIR} ${HDF5_SRC_INCLUDE_DIRS}>` it compiles nicely.

**Expected behavior**

**Platform (please complete the following information)**
 - HDF5 version: tag hdf5-1_14_1 577c192518598c7e2945683655feffcdbdf5a91b
 - OS and version: Windows 10, VS 2022
 - Compiler and version: MSVC
 - Build system (e.g. CMake, Autotools) and version CMake 3.26.4
 - Any configure options you specified: see below
 - MPI library and version (parallel HDF5): nope

**Additional context**
My Cmake code to include the library:
```cmake
set(HDF5_EXTERNALLY_CONFIGURED ON)
set(HDF5_INSTALL_NO_DEVELOPMENT OFF)
set(BUILD_TESTING OFF)
set(HDF5_BUILD_TOOLS OFF)
set(HDF5_BUILD_EXAMPLES OFF)
set(HDF5_BUILD_HL_LIB OFF)
add_subdirectory(hdf5 EXCLUDE_FROM_ALL)
add_library(HDF5::HDF5 ALIAS hdf5-static)
```
Then I link against it in my target
```cmake
target_link_libraries(${TARGET_NAME} HDF5::HDF5)
```

I have verified in my `h5pubconf.h` that the SUBFILING_VFD feature is not build. 
```c++
/* #undef H5_HAVE_SUBFILING_VFD */
```

**Comment by hyoklee** [comment] 2023-06-02 19:21
@diiigle , thank you for your bug report!

Would you mind sharing the GitHub repo that uses hdf5 as a submodule?
I think that will help us to test the fix later.

**Comment by byrnHDF** [comment] 2023-06-02 19:52
The problem is that the header file is in the subfiling folder before being published into the main include (without subfolder) and used in hdf5.h (without subfolder) the solution is too add the subfolder to the include property for building. There should be a recent PR merged for this issue.

**Comment by diiigle** [comment] 2023-06-03 05:57
Thank you both for your quick responses.

I see, my issue is then related to #2422 and #2621 and @byrnHDF is referring to [these PRs](https://github.com/HDFGroup/hdf5/pulls?q=is%3Apr+%232621+is%3Aclosed).

However I think those fixes only applied to the autotools build system and the problem persists with CMake. I have verified the bug again with the most recent 1.14.1-2 tag (which includes this PR).

@hyoklee Unfortunately I don't have a public repo to share. But I see the point of such an integration test, that builds a small reproducer which in turn uses this repo as a submodule. To have the two CMake builds properly separated (namespaces and CACHE variables etc) you'd need a second, recursive CMake process. This could be costly on the CI though, if you're not using a compiler cache like `ccache`.

Is that something you'd be willing to support? IMHO the submodule workflow is [getting popular](https://cliutils.gitlab.io/modern-cmake/chapters/projects/submodule.html) in the CMake ecosystem.

**Comment by byrnHDF** [comment] 2023-06-05 21:30
The CMake was fixed earlier ( I think, but can't locate right now). The change was to add the subdir to the target includes in the src/CMakeLists.txt file.

**Comment by byrnHDF** [comment] 2023-06-05 21:47
Ahh, the use of ${HDF5_SRC_INCLUDE_DIRS} in the PRIVATE property is not enough, it needs to be in the BUILD_INTERFACE too?

**Comment by diiigle** [comment] 2023-06-06 06:54
> Ahh, the use of ${HDF5_SRC_INCLUDE_DIRS} in the PRIVATE property is not enough, it needs to be in the BUILD_INTERFACE too?

Yes, that is what I was proposing. The reason is that HDF5-static is being build and **linked to** from the repository as is, requiring any includes in the same locations that the build of the library did. I presume you are "flattening" the folder structure on `install()` which is not happening in this case.

What is the reasoning for flattening the folder structure in released source packages? Could you keep it the same way as it is stored in the repo (where the folder exists presumably for organizational reasons), and `#include "H5FDsubfiling/H5FDsubfiling.h"`?

**Comment by diiigle** [comment] 2023-06-13 14:53
Thanks for fixing this so quickly. I'll keep the issue open till this lands on a release branch.

Ad integration test: I have discovered how a downstream project (HighFive, Easy C++ HDF5 wrapper) solves [this](https://github.com/BlueBrain/HighFive/blob/master/tests/test_project/CMakeLists.txt).

**Comment by byrnHDF** [comment] 2023-06-13 21:37
Closing this as this has been implemented

**Closed as completed by byrnHDF** 2023-06-13 21:37 UTC
Labels: Component - Build
