### ISSUE TITLE
Compatibility macro issue with clang on MacOS and Ubuntu Linux 

### ISSUE THREAD

**Issue by WardF** [HDFGroup/hdf5#4118] opened 2024-03-12 16:58 UTC
One of the netCDF-C pure-hdf5 tests fails to build after upgrading to the latest MacOS XCode, (clang-1500.3.9.4).  The test fails with the following error, when linking against any libhdf5 > `1.12.0`, built with API Compatibility=110. Linking here from the netCDF-C issue https://github.com/Unidata/netcdf-c/issues/2886.

```
/Users/wfisher/Desktop/gitprojects/netcdf-c/h5_test/tst_h_files4.c:167:64: error: incompatible function pointer types passing 'herr_t (hid_t, const char *, const H5L_info2_t *, void *)' (aka 'int (long long, const char *, const H5L_info2_t *, void *)') to parameter of type 'H5L_iterate1_t' (aka 'int (*)(long long, const char *, const H5L_info1_t *, void *)') [-Wincompatible-function-pointer-types]
         if (H5Literate(grpid, H5_INDEX_CRT_ORDER, H5_ITER_INC, &idx, op_func, 
                                                                      ^~~~~~~
/Users/wfisher/environments/local-serial-1.12.2-ac-clang/include/H5Lpublic.h:1835:42: note: passing argument to parameter 'op' here
                          H5L_iterate1_t op, void *op_data);
```

This failure does not occur when linking against libraries in the `1.10x` branch, nor does it occur on a MacOS system running the previous XCode,  (clang-1500.1.0.2.5).  It appears that maybe something in the latest XCode update is interfering with the API compatibility macros under the hood.

The issue can be fixed by excluding `--with-default-api-version=v110` when building `libhdf5` with versions above `1.12.0`.

It feels like this is an issue with this version of clang, because everything works as expected with an older version, and everything works on my Linux VMs.  Regardless of whether or not we should be using the compatibility macro, they ought to work; that's what they are for.  And they did in-fact work, until the latest XCode update.

**Comment by WardF** [comment] 2024-03-12 17:12
Update to this issue; installing `clang` on a Ubuntu `23.10` desktop system and using it results in the same error.  Building with `gcc` on the same system works.  The version information for each is as follows:

## clang

```
vagrant@vagrant:~/Desktop/gitprojects/netcdf-c/build$ clang -v
Ubuntu clang version 16.0.6 (15)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/12
Found candidate GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/13
Selected GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/13
Candidate multilib: .;@m64
Selected multilib: .;@m64

```

## gcc

```
vagrant@vagrant:~/Desktop/gitprojects/netcdf-c/build$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-linux-gnu/13/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.2.0-4ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Ubuntu 13.2.0-4ubuntu3) 

```

**Comment by derobins** [comment] 2024-03-12 21:48
No worries. We'll take a look and try to get a fix into 1.14.4.

**Comment by derobins** [comment] 2024-03-13 08:00
Hi Ward!

I took a look at the code in question in netcdf-c, and I think the problem is that you are mixing the compatibility macros with explicit `H5_VERSION_GE(1,12,0)` logic. Can you try removing those version checks around line 50 and just use `H5L_info_t`, letting the compatibility macros handle the struct flavor for you? That should let it match the `H5Literate` call where you rely on the compatibility macros.

**Comment by derobins** [comment] 2024-03-13 15:47
https://github.com/Unidata/netcdf-c/pull/2888

**Comment by WardF** [comment] 2024-03-13 20:05
Thanks very much!

**Comment by derobins** [comment] 2024-03-14 14:14
I'm going to go ahead and close this since it's not a bug in HDF5 and they have a fix for their issue.

**Closed as completed by derobins** 2024-03-14 14:14 UTC
Labels: Component - C Library

**Comment by WardF** [comment] 2024-03-14 16:21
Sounds good, I appreciate the information and help! Re: 1.8.x compatibility, we've had that for a while and while I don't mind maintaining it for as long as reasonable, it's also quite old. As you point out, it's not receiving a lot of bug and security attention, so if it ages out, it ages out.  In the upcoming release I'm going to make a note that people should not expect to maintain that; as long as files *written* with 1.8.x remain readable, we will be fine :).  Thanks!
