### ISSUE TITLE
h5fc broken (or changed) in the hdf5_1_14-9f7b987 snapshot

### ISSUE THREAD

**Issue by jefflee-icesat2** [HDFGroup/hdf5#4308] opened 2024-04-02 18:30 UTC
**Describe the bug**
h5fc repeats the source and object filenames in the wrong place in the argument list, resulting in attempting to use the output object as the input file.

gfortran: fatal error: input file 'const_glob_mod.o' is the same as output file

**Expected behavior**
Normal compilation

**Platform (please complete the following information)**
 - HDF5 version: hdf5_1_14-9f7b987
 - OS and version: MacOS Sonoma 14.3.1 
 - Compiler and version: gfortran; gcc version 13.2.0
 - Build system (e.g. CMake, Autotools) and version: ./configure
 - Any configure options you specified: /configure --prefix="${BASEDIR}" --enable-fortran "${EXT_ZLIB}"
 - MPI library and version (parallel HDF5): N/A

**Additional context**

using the -show argument (to see the compile command) with  h5fc in 1.10.8:

../../../base_libs/bin/h5fc -show -J../../modules -fPIC -cpp -DHDF5_1_10 -O2 -g -Wall -Wno-surprising -fcheck=all -fimplicit-none -fbacktrace -ffpe-trap=zero,overflow,invalid -I. -I../../modules -I../../../common_libs/modules -I../../../base_libs/include -c const_glob_mod.f90 -o const_glob_mod.o

yields:

gfortran -I/Users/jelee1/Development/asas_hotfix/base_libs/include -J../../modules -fPIC -cpp -DHDF5_1_10 -O2 -g -Wall -Wno-surprising -fcheck=all -fimplicit-none -fbacktrace -ffpe-trap=zero,overflow,invalid -I. -I../../modules -I../../../common_libs/modules -I../../../base_libs/include -c const_glob_mod.f90 -o const_glob_mod.o

using the -show argument (to see the compile command) with  h5fc in 1_14-9f7b987

../../../base_libs/bin/h5fc -show -J../../modules -fPIC -cpp -DHDF5_1_10 -O2 -g -Wall -Wno-surprising -fcheck=all -fimplicit-none -fbacktrace -ffpe-trap=zero,overflow,invalid -I. -I../../modules -I../../../common_libs/modules -I../../../base_libs/include -c const_glob_mod.f90 -o const_glob_mod.o

gfortran -I/Users/jelee1/Development/asas/base_libs/include -J../../modules -fPIC -cpp -DHDF5_1_10 -O2 -g -Wall -Wno-surprising -fcheck=all -fimplicit-none -fbacktrace -ffpe-trap=zero,overflow,invalid -I. -I../../modules -I../../../common_libs/modules -I../../../base_libs/include **const_glob_mod.f90 const_glob_mod.o** -J../../modules -fPIC -cpp -DHDF5_1_10 -O2 -g -Wall -Wno-surprising -fcheck=all -fimplicit-none -fbacktrace -ffpe-trap=zero,overflow,invalid -I. -I../../modules -I../../../common_libs/modules -I../../../base_libs/include -c const_glob_mod.f90 -o const_glob_mod.o:

Notice the object and source filenames are repeated in the middle of the options strings.

**Comment by brtnfld** [comment] 2024-04-04 16:14
I could not reproduce the error. Can you provide your CC,FC and flags settings and the configure line you used to build the library?

**Comment by jefflee-icesat2** [comment] 2024-04-05 18:59
So, I can temporarily 'fix' this by using the h5fc script from an older library version (1.10.8)

My compile line looks like this:

../../../base_libs/bin/h5fc -J../../modules -fPIC -cpp -DHDF5_1_10 -O2 -g -Wall -Wno-surprising -fcheck=all -fimplicit-none -fbacktrace -ffpe-trap=zero,overflow,invalid -I. -I../../modules -I../../../common_libs/modules -I../../../base_libs/include -c const_glob_mod.f90 -o const_glob_mod.o

I compile the library like this (due to #4310)

configure --prefix="${BASEDIR}" --enable-fortran "${EXT_ZLIB} --disable-nonstandard-feature-float16

My entire config log is within #4310

**Comment by brtnfld** [comment] 2024-04-10 14:27
This issue has been resolved and will be included in the upcoming release. Thank you for bringing this to our attention.

**Closed as completed by brtnfld** 2024-04-10 14:27 UTC
Labels: Component - Tools, Component - Wrappers
