### ISSUE TITLE
ftruncate fails on NFS

### ISSUE THREAD

**Issue by woutdenolf** [HDFGroup/hdf5#468] opened 2021-03-12 12:14 UTC
hdf5 1.10.4

Original issue: https://github.com/h5py/h5py/issues/1859

This fails occasionally (hard to reproduce) when flushing to a file over NFS:
https://github.com/HDFGroup/hdf5/blob/hdf5-1_10_4/src/H5FDsec2.c#L891-L892

Is this a know problem with NFS?

**Comment by epourmal** [comment] 2021-03-24 13:03
Thank you for reporting! We are not aware of the issue. Would it be possible to reproduce the issue with a C program?

Thank you!
Elena

**Comment by derobins** [comment] 2024-01-19 23:05
We'll try to address this for 1.14.4. Keep in mind, the reported HDF5 version is really, really old and no longer supported and we don't see the problem in our testing, despite testing on NFS all the time. If I can't reproduce the problem, I'll have to close this issue. It'd be really helpful if you can check if this issue is still present for you in 1.14.3.

**Comment by derobins** [comment] 2024-03-23 14:22
We have never seen this issue and can't reproduce, despite testing on NFS all the time. Closing.

**Closed as completed by derobins** 2024-03-23 14:22 UTC
Labels: Component - C Library
