### ISSUE TITLE
Unable to build HDF5 in a Slurm based cluster

### ISSUE THREAD

**Issue by Hnair13** [HDFGroup/hdf5#3274] opened 2023-07-25 08:49 UTC
I need HDF5 module to compile a PIC Code. I have used the given steps to build it :
```
git clone -b hdf5-1_14_1-2 https://github.com/HDFGroup/hdf5.git $HOME/src/hdf5
rm -rf $HOME/src/hdf5-build
cmake -S $HOME/src/hdf5 -B $HOME/src/hdf5-build -DBUILD_TESTING=OFF -DHDF5_ENABLE_PARALLEL=ON -DCMAKE_INSTALL_PREFIX=$HOME/sw/hdf5-1.14.1.2
cmake --build $HOME/src/hdf5-build --target install --parallel 8
rm -rf $HOME/src/hdf5-build
```
I am getting the following error while running cmake --build $HOME/src/hdf5-build --target install --parallel 8 :
**gmake[2]: *** [bin/ph5diff] Error 1
gmake[1]: *** [tools/src/h5diff/CMakeFiles/ph5diff.dir/all] Error 2
collect2: error: ld returned 1 exit status
gmake[2]: *** [bin/h5clear] Error 1
gmake[1]: *** [tools/src/misc/CMakeFiles/h5clear.dir/all] Error 2
collect2: error: ld returned 1 exit status
gmake[2]: *** [bin/h5mkgrp] Error 1
gmake[1]: *** [tools/src/misc/CMakeFiles/h5mkgrp.dir/all] Error 2
[ 77%] Built target hdf5-shared
gmake: *** [all] Error 2**

I am using the following modules to configure the HDF5:
CMake/3.23.1-GCCcore-11.3.0
GCC/11.3.0
OpenMPI/4.1.4-GCC-11.3.0

**Comment by byrnHDF** [comment] 2023-07-25 12:40
That is the the tail end - we need to know the root cause of the linking errors.

**Comment by derobins** [comment] 2023-07-25 16:21
This should be addressed in the HDF Forum. Can we move it there? Issues are for bugs that can be fixed, not questions and tech support.

https://forum.hdfgroup.org/

**Comment by derobins** [comment] 2023-07-27 14:45
I'm going to go ahead and close this. Please ask about build problems on the HDF Group forum.

**Closed as completed by derobins** 2023-07-27 14:45 UTC
